resources:
- wordpress
- mysql
patches:
- path: patch.yaml
namePrefix: kustomize-

vars:
- name: WORDPRESS_SERVICE
  objref:
    kind: Service
    name: wordpress
    apiVersion: v1
- name: MYSQL_SERVICE
  objref:
    kind: Service
    name: mysql
    apiVersion: v1

